### ISSUE TITLE
Syntax error for <div>

### ISSUE THREAD

**Issue by bfcns** [feliperenan/heex_formatter#47]
file.html.heex:
```
<div>
<h2 class="font-bold m-4">...
```

```shell
> mix format
```

```
file.html.heex:1:1: syntax error before: '<'
    (elixir 1.12.3) lib/code.ex:978: Code.format_string!/2
    (mix 1.12.3) lib/mix/tasks/format.ex:418: Mix.Tasks.Format.format_file/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by feliperenan** [comment]
Which Elixir version you are using? It works only on 1.13 or higher.

**Comment by feliperenan** [comment]
I'm closing for now. Please, do let me know in case you are still facing this issue after making sure you are Elixir 1.13.
