### ISSUE TITLE
ArgumentError while formatting Unicode text

### ISSUE THREAD

**Issue by oliviasculley** [feliperenan/heex_formatter#50]
Unicode text in `.heex` files seems to crash Heex Formatter :cry:  

## Steps to Reproduce
1. Create `testing.html.heex`, add `😔` or `我愛Phoenix!`
2. Try to format heex template

## Error
```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an iodata term

    :erlang.iolist_to_binary([128532, 10])
    lib/heex_formatter/phases/tokenizer.ex:40: HeexFormatter.Phases.Tokenizer.tokenize/2
    (elixir 1.13.2) lib/enum.ex:1250: anonymous fn/3 in Enum.flat_map_reduce/3
    (elixir 1.13.2) lib/enum.ex:4475: Enumerable.List.reduce/3
    (elixir 1.13.2) lib/enum.ex:1249: Enum.flat_map_reduce/3
    lib/heex_formatter/phases/tokenizer.ex:35: HeexFormatter.Phases.Tokenizer.run/2
    lib/heex_formatter.ex:17: HeexFormatter.format/2
    (mix 1.13.2) lib/mix/tasks/format.ex:561: Mix.Tasks.Format.format_file/2
```

Please let me know if you need any additional information! As far as I'm aware, I'm using the latest version of Heex Formatter.

**Comment by feliperenan** [comment]
Hi @oliviasculley 

Looks like you are using an older version of heex formatter. Could you try to update it and try again? 🙏🏻 

To make sure you are using the latest, try this:

```
mix deps.unlock heex_formatter
mix deps.get
mix compile
```

After that you should see a diff similar to this one on your `mix.exs`:

```diff
-  "heex_formatter": {:git, "https://github.com/feliperenan/heex_formatter.git", "4da30c408033facd7153e703fd0eb31161d00221", []},
+  "heex_formatter": {:git, "https://github.com/feliperenan/heex_formatter.git", "c11931eb8f7e71f2f90fc9c77345a070d757b51b", []},
```

Thanks

**Comment by oliviasculley** [comment]
Yep that seems to have fixed it, sorry about that and thank you!
